# Generated by Django 3.1.1 on 2020-10-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201001_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenary',
            name='detail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='itenary',
            name='number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tagforprod',
            name='tags',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
