# Generated by Django 3.1.1 on 2020-10-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20201006_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
