# Generated by Django 3.1.1 on 2020-10-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20201008_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
