# Generated by Django 3.1.1 on 2020-10-13 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20201008_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagforprod',
            name='product',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.DeleteModel(
            name='TagForProd',
        ),
    ]
