# Generated by Django 3.1.1 on 2020-10-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20201013_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='payment',
        ),
        migrations.AddField(
            model_name='product',
            name='itenary',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pimage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/products/'),
        ),
        migrations.DeleteModel(
            name='itenary',
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
