# Generated by Django 3.1.1 on 2020-10-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20201021_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='loca_city',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
    ]
