# Generated by Django 3.1.1 on 2020-10-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='adventuretype',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
