# Generated by Django 3.1.1 on 2020-10-22 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20201022_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pimage',
        ),
    ]
