# Generated by Django 3.1.1 on 2020-10-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_product_pimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='des',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='itenary',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
